name: "Setup PlatformIO"
description: "Set up platformIO Core and add pio to PATH"
inputs:
  platformio-version:
    description: "PlatformIO version to use. (e.g. 5.2.5, 5.2 or 5"
    default: "newest"
    
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
    - run: pip install platformio
      shell: bash
      if: ${{ inputs.platformio-version == 'newest' }}
    - run: pip install platformio==${{ inputs.platformio-version }}
      shell: bash
      if: ${{ inputs.platformio-version != 'newest' }}

branding:
  icon: "terminal"
  color: "orange"
