name: Bug report
description: Create a report to help us improve
title: ":bug: Bug report: <title>"
labels: bug
assignees:
  - n-vr

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe the current behavior
      placeholder: A clear concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe the expected behavior
      placeholder: A clear concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Change this file '...'
        2. Run the action
        3. See error on step '...'
    validations:
      required: false

  - type: input
    attributes:
      label: Action version
      description: What version of the action are you using?
      placeholder: e.g. v1.0.0
    validations:
      required: true

  - type: input
    attributes:
      label: PlatformIO version
      description: What version of PlatformIO did you specify?
      placeholder: e.g. newest or v5.2.5
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Relevant workflow configuration
      description: Please copy and paste any relevant workflow configuration. This will be automatically formatted into yaml, so no need for backticks.
      render: yaml
    validations:
      required: false

  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

#   - type: checkboxes
#     attributes:
#       label: Code of Conduct
#       description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#       options:
#         - label: I agree to follow this project's Code of Conduct
#           required: true
