name: Feature request
description: Suggest an idea for this project
title: ":zap: Feature request: <title>"
labels: enhancement
assignees:
  - n-vr

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for the same functionality.
      options:
      - label: I have searched the existing feature requests
        required: true

  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
